apiVersion: v1
kind: ConfigMap
metadata:
    name: todo-app-backend-config
    namespace: project
data:
    PORT: "3000"
    IMAGE_URL: "https://picsum.photos/1200"
    IMAGE_PATH: "volume/image.png"
