apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app-backend
    namespace: project
spec:
    replicas: 1
    selector:
        matchLabels:
            app: todo-app-backend
    template:
        metadata:
            labels:
                app: todo-app-backend
        spec:
            volumes:
                - name: image-volume
                  persistentVolumeClaim:
                      claimName: image-claim
            containers:
                - name: todo-app-backend
                  image: aitoaarni/todo-app-backend:2.2
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: image-volume
                        mountPath: /app/volume
                  ports:
                      - containerPort: 3000
