apiVersion: apps/v1
kind: Deployment
metadata:
    name: hashgenerator-dep
    namespace: exercises

spec:
    replicas: 1
    selector:
        matchLabels:
            app: logoutput
    template:
        metadata:
            labels:
                app: logoutput

        spec:
            volumes:
                - name: shared-file
                  emptyDir: {}
                - name: config-volume
                  configMap:
                      name: logoutput-config
            containers:
                - name: logoutput-endpoint
                  image: aitoaarni/logoutput-endpoint:2.5
                  ports:
                      - containerPort: 8000
                  volumeMounts:
                      - name: shared-file
                        mountPath: /usr/src/app/volume
                  imagePullPolicy: Always

                - name: logoutput
                  image: aitoaarni/logoutput:2.5

                  volumeMounts:
                      - name: shared-file
                        mountPath: /usr/src/app/volume
                      - name: config-volume
                        mountPath: /usr/src/app/config
                        readOnly: true
                  env:
                      - name: MESSAGE
                        valueFrom:
                            configMapKeyRef:
                                name: logoutput-config
                                key: MESSAGE
