apiVersion: v1
kind: Service
metadata:
    name: pingpong-svc
spec:
    type: ClusterIP
    selector:
        app: pingpong
    ports:
        - port: 5678
          targetPort: 8000
          protocol: TCP
