apiVersion: apps/v1
kind: Deployment
metadata:
    name: pingpong-dep
    namespace: exercises
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pingpong
    template:
        metadata:
            labels:
                app: pingpong
        spec:
            # volumes:
            # - name: persistent-volume
            #   persistentVolumeClaim:
            #   claimName: image-claim1
            containers:
                - name: pingpong
                  image: aitoaarni/ping-pong:3.2
                  ports:
                      - containerPort: 8000
                  env:
                      - name: DB_HOST
                        value: "postgres-svc"
                      - name: DB_NAME
                        value: "mydb"
                      - name: DB_USER
                        value: "myuser"
                      - name: DB_PASSWORD
                        value: "mypassword"
                      - name: DB_PORT
                        value: "5432"
                #   volumeMounts:
                #   - name: persistent-volume
                # mountPath: /usr/src/app/persistentVolume
