apiVersion: apps/v1
kind: Deployment
metadata:
    name: pingpong-dep

spec:
    replicas: 1
    selector:
        matchLabels:
            app: pingpong
    template:
        metadata:
            labels:
                app: pingpong
        spec:
            volumes:
                - name: persistent-volume
                  persistentVolumeClaim:
                      claimName: image-claim1
            containers:
                - name: pingpong
                  image: aitoaarni/ping-pong:1.11
                  ports:
                      - containerPort: 8000
                  volumeMounts:
                      - name: persistent-volume
                        mountPath: /usr/src/app/persistentVolume
